/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Welcome
         * @description Default root route provided by h4ckath0n.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/passkey/add/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finish adding a passkey
         * @description Verify the WebAuthn attestation and attach the new passkey to the user.
         */
        post: operations["add_finish_auth_passkey_add_finish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/passkey/add/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start adding a passkey
         * @description Begin adding a new passkey for the authenticated user and return registration options.
         */
        post: operations["add_start_auth_passkey_add_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/passkey/login/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finish passkey login
         * @description Finish passkey login by verifying the WebAuthn assertion for the flow and binding an optional device key.
         */
        post: operations["login_finish_auth_passkey_login_finish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/passkey/login/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start passkey login
         * @description Begin a username-less passkey login ceremony and return WebAuthn authentication options.
         */
        post: operations["login_start_auth_passkey_login_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/passkey/register/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finish passkey registration
         * @description Finish passkey registration by verifying the WebAuthn attestation for the flow and binding an optional device key.
         */
        post: operations["register_finish_auth_passkey_register_finish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/passkey/register/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start passkey registration
         * @description Begin a passkey registration ceremony. Creates a new user and a single-use challenge flow, then returns WebAuthn registration options.
         */
        post: operations["register_start_auth_passkey_register_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/passkeys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List passkeys
         * @description List all passkeys, including revoked entries, for the current user.
         */
        get: operations["passkeys_list_auth_passkeys_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/passkeys/{key_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke a passkey
         * @description Revoke a passkey by its internal key ID. The last active passkey cannot be revoked and returns the LAST_PASSKEY error.
         */
        post: operations["passkey_revoke_auth_passkeys__key_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/echo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Demo echo
         * @description Echo back the message along with its reverse.
         */
        post: operations["demo_echo_demo_echo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Demo ping
         * @description Simple liveness ping for the demo namespace.
         */
        get: operations["demo_ping_demo_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/sse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Demo SSE stream
         * @description Authenticated SSE stream that simulates chunked output. Requires a device JWT with aud set to h4ckath0n:sse.
         */
        get: operations["demo_sse_demo_sse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Basic health check for the app.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Readiness check for E2E and deployment probes.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** EchoRequest */
        EchoRequest: {
            /**
             * Message
             * @description Message to echo back.
             */
            message: string;
        };
        /** EchoResponse */
        EchoResponse: {
            /**
             * Message
             * @description Original message.
             */
            message: string;
            /**
             * Reversed
             * @description Reversed message.
             */
            reversed: string;
        };
        /**
         * ErrorResponse
         * @description Standard error envelope for auth routes.
         */
        ErrorResponse: {
            /**
             * Detail
             * @description Error detail message or structured error payload.
             */
            detail: string | {
                [key: string]: string;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @description Health status string.
             */
            status: string;
        };
        /** HealthzResponse */
        HealthzResponse: {
            /**
             * Status
             * @description Health check status.
             */
            status: string;
        };
        /** PasskeyAddFinishRequest */
        PasskeyAddFinishRequest: {
            /**
             * Credential
             * @description Browser PublicKeyCredential response as JSON.
             */
            credential: {
                [key: string]: unknown;
            };
            /**
             * Device Label
             * @description Optional label for the device.
             */
            device_label?: string | null;
            /**
             * Device Public Key Jwk
             * @description Optional device public key in JWK format to bind a device identity.
             */
            device_public_key_jwk?: {
                [key: string]: unknown;
            } | null;
            /**
             * Flow Id
             * @description Flow ID returned by add/start.
             */
            flow_id: string;
        };
        /** PasskeyAddStartResponse */
        PasskeyAddStartResponse: {
            /**
             * Flow Id
             * @description Server-generated flow ID for add passkey.
             */
            flow_id: string;
            /**
             * Options
             * @description PublicKeyCredentialCreationOptions payload as a JSON-safe dict.
             */
            options: {
                [key: string]: unknown;
            };
        };
        /** PasskeyFinishResponse */
        PasskeyFinishResponse: {
            /**
             * Device Id
             * @description Device ID that starts with the d prefix, empty when no device key is bound.
             */
            device_id: string;
            /**
             * Display Name
             * @description Optional display name for the user, not set by default.
             */
            display_name?: string | null;
            /**
             * Role
             * @description Server-side role for the user.
             */
            role: string;
            /**
             * User Id
             * @description User ID that starts with the u prefix.
             */
            user_id: string;
        };
        /** PasskeyInfo */
        PasskeyInfo: {
            /**
             * Created At
             * Format: date-time
             * @description Creation timestamp in UTC.
             */
            created_at: string;
            /**
             * Id
             * @description Internal passkey ID that starts with the k prefix.
             */
            id: string;
            /**
             * Label
             * @description Optional passkey nickname.
             */
            label?: string | null;
            /**
             * Last Used At
             * @description Last successful use timestamp.
             */
            last_used_at?: string | null;
            /**
             * Revoked At
             * @description Revocation timestamp, if revoked.
             */
            revoked_at?: string | null;
        };
        /** PasskeyListResponse */
        PasskeyListResponse: {
            /**
             * Passkeys
             * @description Passkeys for the current user.
             */
            passkeys: components["schemas"]["PasskeyInfo"][];
        };
        /** PasskeyLoginFinishRequest */
        PasskeyLoginFinishRequest: {
            /**
             * Credential
             * @description Browser PublicKeyCredential response as JSON.
             */
            credential: {
                [key: string]: unknown;
            };
            /**
             * Device Label
             * @description Optional label for the device.
             */
            device_label?: string | null;
            /**
             * Device Public Key Jwk
             * @description Optional device public key in JWK format to bind a device identity.
             */
            device_public_key_jwk?: {
                [key: string]: unknown;
            } | null;
            /**
             * Flow Id
             * @description Flow ID returned by login/start.
             */
            flow_id: string;
        };
        /** PasskeyLoginStartResponse */
        PasskeyLoginStartResponse: {
            /**
             * Flow Id
             * @description Server-generated flow ID for login.
             */
            flow_id: string;
            /**
             * Options
             * @description PublicKeyCredentialRequestOptions payload as a JSON-safe dict.
             */
            options: {
                [key: string]: unknown;
            };
        };
        /** PasskeyRegisterFinishRequest */
        PasskeyRegisterFinishRequest: {
            /**
             * Credential
             * @description Browser PublicKeyCredential response as JSON.
             */
            credential: {
                [key: string]: unknown;
            };
            /**
             * Device Label
             * @description Optional label for the device.
             */
            device_label?: string | null;
            /**
             * Device Public Key Jwk
             * @description Optional device public key in JWK format to bind a device identity.
             */
            device_public_key_jwk?: {
                [key: string]: unknown;
            } | null;
            /**
             * Flow Id
             * @description Flow ID returned by register/start.
             */
            flow_id: string;
        };
        /** PasskeyRegisterStartResponse */
        PasskeyRegisterStartResponse: {
            /**
             * Flow Id
             * @description Server-generated flow ID for registration.
             */
            flow_id: string;
            /**
             * Options
             * @description PublicKeyCredentialCreationOptions payload as a JSON-safe dict.
             */
            options: {
                [key: string]: unknown;
            };
        };
        /** PasskeyRevokeResponse */
        PasskeyRevokeResponse: {
            /**
             * Message
             * @description Status message for the revocation action.
             */
            message: string;
        };
        /** PingResponse */
        PingResponse: {
            /**
             * Ok
             * @description True when the service is reachable.
             */
            ok: boolean;
        };
        /** RootResponse */
        RootResponse: {
            /**
             * Message
             * @description Welcome message.
             */
            message: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RootResponse"];
                };
            };
        };
    };
    add_finish_auth_passkey_add_finish_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasskeyAddFinishRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeyFinishResponse"];
                };
            };
            /** @description Invalid or expired flow, or WebAuthn verification error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_start_auth_passkey_add_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeyAddStartResponse"];
                };
            };
            /** @description Missing or invalid token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    login_finish_auth_passkey_login_finish_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasskeyLoginFinishRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeyFinishResponse"];
                };
            };
            /** @description Invalid credentials, revoked passkey, or expired flow. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_start_auth_passkey_login_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeyLoginStartResponse"];
                };
            };
        };
    };
    register_finish_auth_passkey_register_finish_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasskeyRegisterFinishRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeyFinishResponse"];
                };
            };
            /** @description Invalid or expired flow, or invalid WebAuthn payload. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_start_auth_passkey_register_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeyRegisterStartResponse"];
                };
            };
            /** @description Invalid request or WebAuthn configuration error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    passkeys_list_auth_passkeys_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeyListResponse"];
                };
            };
            /** @description Missing or invalid token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    passkey_revoke_auth_passkeys__key_id__revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeyRevokeResponse"];
                };
            };
            /** @description Missing or invalid token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Passkey not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Cannot revoke the last active passkey. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": {
                     *         "code": "LAST_PASSKEY",
                     *         "message": "Cannot revoke the last active passkey."
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_echo_demo_echo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EchoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EchoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_ping_demo_ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PingResponse"];
                };
            };
        };
    };
    demo_sse_demo_sse_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event stream with chunk and done events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/event-stream": string;
                };
            };
            /** @description Missing or invalid device JWT. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Missing token"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthzResponse"];
                };
            };
        };
    };
}
